#!/bin/bash

argument_count=$#

if [ $argument_count == 0 ]; then 
  echo "jv: Requires command"
  exit 1
fi

command_count=$(jq -r '.commands | length' 'commands.json')
echo 'jv: Command Count: ' $command_count
